=== MatthewGotte/Tuks-UP-COS-Varisty/Second Year/IMY210/06_07_Exam/Exam Files/B - DTD/dtd-xml.dtd
<!--Matthew Gotte, u20734621-->
<!ELEMENT sal  ( (sword , axe , lance)  | ( player+, round+ ) )>

<!ATTLIST sal 
icon CDATA #IMPLIED
>

<!--(sword, axe, lance)-->
<!ELEMENT sword  EMPTY>
<!ELEMENT axe  EMPTY>

<!ELEMENT lance  EMPTY>

<!ATTLIST sword
beat CDATA #IMPLIED
>

<!ATTLIST axe
beat CDATA #REQUIRED
>

<!ATTLIST lance
beat CDATA #REQUIRED
>

<!--(player+, round+)-->

<!ELEMENT player  EMPTY>
<!ELEMENT round  ( unit+ )>

<!ATTLIST player
name CDATA #REQUIRED
>

<!ATTLIST round
winner CDATA #IMPLIED
>


<!--( unit+ ) & unit-->
<!ELEMENT unit  (sword?)>
<!ATTLIST unit
name CDATA #REQUIRED
>

=== MatthewGotte/Tuks-UP-COS-Varisty/Second Year/IMY210/06_07_Exam/Exam Files/B - DTD/dtd-xml_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sal SYSTEM "dtd-xml.dtd">
<sal icon="sal">
	<player name="Tom"/>
	<player name="Sally"/>
	
	<round winner="Tom">
		<unit name="eli"/>
		<unit name="lyn"/>
	</round>

	<round>
		<unit name="eli"/>
		<unit name="eli"/>
	</round>

	<round winner="Sally">
		<unit name="mika"/>
		<unit name="hector"/>
	</round>
	
	<round winner="Sally">
		<unit name="nina"/>
		<unit name="eli"/>
	</round>
</sal>
